### ISSUE TITLE
Set up an LDAP server in the VM

### ISSUE THREAD

**Issue by lonnen** [rhelmer/socorro-vagrant#1]
An LDAP server allows local installs to use a proper auth module, which will enable sessions. Sessions are required for testing Client messaging.

**Comment by rhelmer** [comment]
Little trickier than I assumed it would be, but looks doable. Just to set a baseline, I started by testing from my dev VM to the (working) Mozilla LDAP server via VPN.

However, looks like we have a bunch of hardcoded assumptions that non-SSL == "dev mode", so the admin pages don't seem to work right in LDAP mode without SSL. Probably easiest to just enable SSL in the VM, although we'll need to use a snakeoil cert I guess.
