### ISSUE TITLE
install oracle java from somwhere other than partner repo

### ISSUE THREAD

**Issue by rhelmer** [rhelmer/socorro-vagrant#16]
Oracle changed their licensing terms so Canonical must remove it from the partner repo (where we install it from now), https://wiki.ubuntu.com/JavaTeam has some details.

AFAIK only Oracle java is supported by hbase and elastic search, so I think we'll want to continue using it instead of openjdk (which is in the main repo).

I'll investigate, but I suspect we'll probably have to just use a script to download and install direct from Oracle.

**Comment by xni** [comment]
May be it's possible to switch to openJDK? Have anyone made such test?

**Comment by rhelmer** [comment]
I have heard anecdotally that OpenJDK doesn't work as well, I'll try to qualify that.

**Comment by rhelmer** [comment]
verbiage on http://wiki.apache.org/hadoop/HadoopJavaVersions sounds scary enough

**Comment by rhelmer** [comment]
Here's a fix https://github.com/rhelmer/socorro-vagrant/commit/1d40e130fa469da140e5f4cd617b1f5e61b9fa93
