### ISSUE TITLE
Collate problems with postgres-9.0

### ISSUE THREAD

**Issue by lonnen** [rhelmer/socorro-vagrant#5]
[default] notice: /Stage[main]/Socorro-db/Exec[/usr/bin/psql -c "INSERT INTO productdims (product, version, branch) values ('GenericProduct', '1.0', '1.0')" breakpad]/returns: ERROR:  could not determine which collation to use for string comparison

notice: /Stage[main]/Socorro-db/Exec[/usr/bin/psql -c "INSERT INTO productdims (product, version, branch) values ('GenericProduct', '1.0', '1.0')" breakpad]/returns: HINT:  Use the COLLATE clause to set the collation explicitly.

err: /Stage[main]/Socorro-db/Exec[/usr/bin/psql -c "INSERT INTO productdims (product, version, branch) values ('GenericProduct', '1.0', '1.0')" breakpad]/returns: change from notrun to 0 failed: /usr/bin/psql -c "INSERT INTO productdims (product, version, branch) values ('GenericProduct', '1.0', '1.0')" breakpad returned 1 instead of one of [0] at /tmp/vagrant-puppet/manifests/classes/socorro-db.pp:102

notice: /Stage[main]/Socorro-db/Exec[/usr/bin/psql -c "INSERT INTO product_visibility (productdims_id, start_date, end_date, featured) VALUES (1, '2010-11-05', '2015-02-05', true)" breakpad]: Dependency Exec[/usr/bin/psql -c "INSERT INTO productdims (product, version, branch) values ('GenericProduct', '1.0', '1.0')" breakpad] has failures: true

warning: /Stage[main]/Socorro-db/Exec[/usr/bin/psql -c "INSERT INTO product_visibility (productdims_id, start_date, end_date, featured) VALUES (1, '2010-11-05', '2015-02-05', true)" breakpad]: Skipping because of failed dependencies

**Comment by rhelmer** [comment]
Hmm did you do a "destroy" since having the issues with 9.1?

I am trying a destroy/up right now, will let you know if it works for me..

**Comment by lonnen** [comment]
That worked. Looks good now.
