### ISSUE TITLE
Provide an alias for redeploy

### ISSUE THREAD

**Issue by lonnen** [rhelmer/socorro-vagrant#8]
Redeployment currently entails:

```
    sudo su vagrant
    sudo /opt/ruby/bin/puppet /vagrant/manifests/init.pp
    .... wait ....
    sudo su socorro
```

There should be an alias or a script that is in the path for the socorro user such that `redeploy` or some similar command pushes the current repo out without making the talking monkey switch users, lose their bash history, remember where puppet is, remember where the init script is, etc.

**Comment by rhelmer** [comment]
I have been thinking lately we should have a "socorro" command that supports subcommands, such as:

socorro restart
socorro deploy

I could foresee adding things like "socorro config --set databasePassword='blah'"

We can fix up socorro user's paths so it runs out of ~/dev/socorro/ and also has the superuser paths set up (so you don't need to su to vagrant user to run puppet).

**Comment by lonnen** [comment]
that++

**Comment by rhelmer** [comment]
Is this still desirable, if we're using shared folders and "vagrant provision" (or "vagrant reload") works reliably to install and restart associated services?

**Comment by lonnen** [comment]
I don't think so, as long as vagrant provision is reliable. I'll reopen if there are problems with the new setup
