### ISSUE TITLE
Inconsistent product list functionality

### ISSUE THREAD

**Issue by vian** [rhelmer/socorro-vagrant#9]
I've found an issue. I've added 2 of my products into breakpad database tables. When I switch from one to another - I don't get my product list on http://crash-stats/ page ("Product:" combobox), instead of it I get a list of Mozilla products. This may be the source of data not displaying on main page bug also.

**Comment by rhelmer** [comment]
Can you retry this with a fresh vagrant install ("vagrant destroy && vagrant up") ?

You should get a working DB out-of-the-box now, thanks to the work documented in http://socorro.readthedocs.org/en/latest/populatepostgres.html
